### ISSUE TITLE
Error using AWEA analysis tool

### ISSUE THREAD

**Issue by dbutrovski** [TerriaJS/aremi-natmap#112]
User reported that Australian Wave Energy Atlas (AWEA) Annual Bivariate Probability Distribution tool is not working. Confirmed by GA, attempting to run the processing service, once input parameters are populated, returns immediately the following error message:

An error occurred
AREMI experienced an error. Please report this by emailing aremi@ga.gov.au. Details of the error are below.
Request has failed.
OK

**Comment by uwer** [comment]
Hi 'dbutrovski'

Firstly the process is working, however the 'study area' is missing so it be rather difficult to select a location correctly. I will investigate the latter (the extraction is too slow though, even though it trawls through 300 000 records)
![processworking](https://user-images.githubusercontent.com/906814/27114177-11d44c48-5105-11e7-82a9-d243bb77a069.png)

**Comment by dbutrovski** [comment]
So, if I understand correctly, user has to click on a location within the study area otherwise WPS fails? Is it possible for the service to better handle 'out-of-bounds' input parameters, or at least show the study area at the time input parameters are set by user?

**Comment by kring** [comment]
AREMI does show the study area when asking you to select a point, but unfortunately it is not working right now.  The problem is that we're currently receiving responses like this for some of the study area map tiles:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?><!DOCTYPE ServiceExceptionReport SYSTEM "http://oa-gis.csiro.au/geoserver/schemas/wms/1.1.1/WMS_exception_1_1_1.dtd"> <ServiceExceptionReport version="1.1.1" >   <ServiceException>
      Internal error 
Server returned HTTP error code 503 for URL http://waveatlas.marine.csiro.au/geoserver/ows?REQUEST=GetCapabilities&amp;VERSION=1.3.0&amp;SERVICE=WMS
</ServiceException></ServiceExceptionReport>
```

Upon further investigation, it looks like we're getting this from the NationalMap/AREMI proxy but _not_ when we ask the server directly for the tiles.  Most likely the server was previously generating these errors, and they have been cached by the proxy.  This happens because the WPS is returning errors using HTTP code 200, which the proxy quite reasonably considers to be success (even though the content is not what we'd like).  OGC services are famous for this (returning errors with an HTTP success code).

**Comment by uwer** [comment]
The WPS does handle that but it is not propagated, I'll see to that it is. As to showing the study area - that was a request we had to the TerriaJS team but not implemented and we did that in our demo version together with other items.
Cache - yes an issue we are aware of. The service was down last week because the underlying infrastructure failed, most of that is back on line (at least for our services), we planning to migrate these to a more reliable environment.

**Comment by kring** [comment]
> As to showing the study area - that was a request we had to the TerriaJS team but not implemented

As mentioned above, it is implemented, it's just not working at the moment because of the cached errors.  Unless I don't know what you mean?

**Comment by uwer** [comment]
The study area is a separate layer presented as top layer entry under the wave atlas, what Dmitar is referring to is 'show the study area at the time input parameters are set by user' - meaning turn up automatically when the analysis processes are active or the like - which was the request I referred to. 
It is implemented yes, but needs to be added manually - we are talking about the same.
The layer should be back on reload - I just tried.
Ditmar: in the meta data of the 'study area' layer it is mentioned that analysis processes are only available there.

**Comment by kring** [comment]
> what Dmitar is referring to is 'show the study area at the time input parameters are set by user' - meaning turn up automatically when the analysis processes are active or the like

yeah, we implemented this.  When you click "Select location", the analysis study area appears on the map.  Looks like it's at least mostly working again, too.

**Comment by uwer** [comment]
haaaa - you did - first time I see it, great!

**Comment by AnaBelgun** [comment]
This has been resolved.
