### ISSUE TITLE
Investigate Australian Wave Energy Atlas issues with HTTPS

### ISSUE THREAD

**Issue by axman6** [TerriaJS/aremi-natmap#135]
We've had user feedback that AWAVEA doesn't work when AREMI is loaded over HTTPS. It seems the AWAVEA team have also redirected their tool to AREMI, and the redirect is to the HTTPS url. We need to find a solution to the analytics being loaded over HTTP, either by proxying the requests, or calling the analytics over HTTPS.

**Comment by meh9** [comment]
From memory we made AWAVEA use CORS because we had problems passing the POSTs through the proxy. I think that problem was fixed some time ago, so we should test just doing it through the proxy.

Might be enough to remove them from here and test that everything works:

https://github.com/TerriaJS/aremi-natmap/blob/master/datasources/aremi/root.ejs#L5

**Comment by a-stacey** [comment]
This was not enough, we had to also add "csiro.au:80" to "allowProxyFor" because the URL explicitly includes port 80 (and so therefor was not been sent via the proxy), this is workaround rather then a true fix for this so we will leave the issue open until we work out whether there is a better way to handle the explicit port in the URL.

**Comment by a-stacey** [comment]
After discussion with  meh9 and kring we have decided that we will not address this further as the port number in the URL is an edge case.
