### ISSUE TITLE
Allow users to edit WPS input fields

### ISSUE THREAD

**Issue by meh9** [TerriaJS/aremi-natmap#136]
We had a request on #130 to be able to enter custom coordinates in the input field to the WPS location. That's a reasonable thing to do, so we should support that. To clarify, in this case it is the lat/lon field of the AWAVEA processes:

<img width="1055" alt="screen shot 2017-07-24 at 12 14 31" src="https://user-images.githubusercontent.com/5283003/28505739-d8866c30-7069-11e7-978a-1c8325ebb9a3.png">

**Comment by a-stacey** [comment]
During development I worked out the following two workarounds which can be used until this feature is implemented:
1) Copy and paste the lat log directly and correctly formatted into the field. (i.e. copy and pasting in `131.036111, -25.345` directly should work).
2) Enter the "," as the first character and then enter select and replace the NaN (i.e. highlight NaN as a single value and then enter a number).
This is because the field must validate correctly in any one single edit.

I have pushed my work in progress to a branch, but talking with @meh9 work is still needed on the UX of how this will function. 
The current implementation:
1) Has placeholder text in the field so that the format that the user is trying to get is clear.
2) Validates the user entry once they have left the field. This allows the user to enter temporarily invalid values (such as "142" which is invalid as it has no Log) and then validates once the control looses focus. The current implemention just resets the field to empty if the value isn't valid (I also tried resetting to a "valid" value: NaN, NaN which is doable but probably not a better implementation).

The issues with the current implementation are:
1) The placeholder text appears in the same colour as the entered text (which is grey) and so it looks like the field is complete even though it has no data (and given that it is already grey and not say black its not exactly clear to make it a sensible colour to show that it is a shadow help text input - i.e. black when entered and light grey when the help text is just in place).
2) When the field resets the value because they have entered an invalid value it is reset to "" which means that the placeholder text is shown again and its not exactly the best user experience. As mentioned I also tried resetting to "NaN, NaN" which is workable but not really the prettiest or cleanest solution. We could explicitly warn the user that there input has be detected as invalid and is being reset, but this seems overly cumbersome.

**Comment by a-stacey** [comment]
Two possible alternate ideas for the UX:
1) Display meta info as the help text so something along the lines of "Lon.###, -Lat.###", "EEE.eee, -SSS.sss", "000.000, -000.000" instead of "131.036111, -25.345", this format matches more nicely with the other fields help text which display "dd/mm/yyyy 00:00", but its not exactly clear what meta text is meaningful.
2) Display text as red when it is placeholder and/or invalid.

**Comment by meh9** [comment]
@philipgrimmett we can't think of a good way to give the user a hint about what to enter for lat/lon in a field, thoughts?

**Comment by meh9** [comment]
@a-stacey 

> 2. Display text as red when it is placeholder and/or invalid.

This is a good idea.

**Comment by a-stacey** [comment]
Also if possible and easy should reverse the Lat/Lon field order (so that it is Lat / Lon rather then Lon / Lat) so that it is more intuitive.

**Comment by a-stacey** [comment]
@philipgrimmett this is the thing you should look at.

**Comment by philipgrimmett** [comment]
Not sure how much effort will be required to implement, but I'd recommend the following changes:
- Disable the 'Run Analysis button' until all required fields are valid, or throw a helpful error listing required fields that have invalid input
- Display validation errors after the invalid field looses focus
- Retain invalid input so users can see what needs to be changed
- Remove validation errors as soon as input is valid

Video: 
https://drive.google.com/file/d/1L-amtafSO287Gnip1prJla04NlT7-uxm/view?usp=sharing

Invision: 
https://invis.io/FCJ32SXRDKH#/298240679_1_-_Default_State

**Comment by a-stacey** [comment]
@philipgrimmett looks good.

@meh9 if you could just review what @philipgrimmett proposes and see if it seems sane to you to I will look at getting this implemented when I get back on Thursday.

**Comment by meh9** [comment]
@a-stacey yep, that looks very good to me, go for it. :)

**Comment by a-stacey** [comment]
With regard to: 
> Also if possible and easy should reverse the Lat/Lon field order (so that it is Lat / Lon rather then Lon / Lat) so that it is more intuitive.

The field title "Longitude and Latitude point (required)" comes from the WPS query.

```
<Input minOccurs="1" maxOccurs="1">
        <ows:Identifier>LonLatPosition</ows:Identifier>
        <ows:Title>Longitude and Latitude point</ows:Title>
        <ComplexData>
          <Default>
            <Format>
              <MimeType>application/vnd.geo+json</MimeType>
              <Schema>http://geojson.org/geojson-spec.html#point</Schema>
            </Format>
          </Default>
          <Supported>
            <Format>
              <MimeType>application/vnd.geo+json</MimeType>
              <Schema>http://geojson.org/geojson-spec.html#point</Schema>
            </Format>
          </Supported>
        </ComplexData>
      </Input>
```

Discussing with @meh9 we have decided to leave it in this order to save confusion between the heading and the input.

**Comment by kring** [comment]
I believe this is done, closing.
