### ISSUE TITLE
AREMI v2017-07-25 pre-release test - Region names not recognised error - Comments

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#142]
AREMI v2017-07-25 pre-release test - Region names not recognised error (#141)

Some comments from observation:

- In the Add Data window there are three options for a catalogue entry (see Attached slide)
(A) - to display the description of the layer only
(B) - the (+) sign to add it to Map
(C) - the 'Add to the map' button to add it to map
It appears that clicking on SOME layer name (A) starts to load the map and generates the error message. This has been noted in SOME layer names of the recently tested National Map version as well..
- It seems that the data is displaying correctly despite of the error message
- The error messages do not reappear on second attempt.

![slide5](https://user-images.githubusercontent.com/22827786/28697660-e0a7d0d8-7380-11e7-9eac-89dc6a803202.JPG)

**Comment by meh9** [comment]
Thanks for the comments.

In reverse order:

1. Yes, we only show those error messages once per layer per session. If you close the tab and open the page again you will see the error message again.
2. In this case it looks like the data is being displayed correctly, but in fact it's not. What the error message is saying is that it was trying to region map a particular region from the data (or regions, some of the error messages show a lot of id's), but that region id could not be found on the region map. When this happens, that region will simply not be displayed. Worse than that, if any of the region id's have been reassigned, it will show the wrong data for that region.
3. Because clicking the name of the layer will actually load it on the preview map on the right, you will see the error message then. As we have then showed it to you we do not show it again if you do go ahead to add the layer. And yes, the (+) and the Add To The Map buttons do the same thing.
