### ISSUE TITLE
AREMI v2017-09-22 pre-release test - 2017 Network Opportunities Constraint Maps - Error

### ISSUE THREAD

**Issue by TheAngeloPace** [TerriaJS/aremi-natmap#166]
Major Issue:

- '2017 Network Opportunities Constraint Maps' data layer appears not present

Comment:

The above data layer is not visible in the Data Catalog navigator and search fails to find it by name

![slide1](https://user-images.githubusercontent.com/20634718/30842955-605858da-a2c9-11e7-84ca-4548e61ad50e.JPG)

**Comment by axman6** [comment]
@TheAngeloPace Thanks for the report - the dataset you're searching for is the one you're looking at in the image. As it is the current data, it is not labeled with the year, only previous year's data will be labeled with the year. We don't image many, if any users would search for that whole string, but are more likely to search for terms such as "network opportunities", which does find the result. This particular dataset is quite well advertised, along with instructions to users for how to access it, so I would say that this issue is minor at most. @meh9 may have more to add.

**Comment by meh9** [comment]
The Changelog item reads:

* Added in the 2017 Network Opportunities Constraint maps in "Electricity Infrastructure -> Network Opportunities" from the Institute for Sustainable Futures, UTS.

As the "2017..." isn't quoted that isn't actually the name of any layer, and you can therefore not find it. If you were to search for any of the quoted strings in the changelog entry then it would find those respective groups. You can also follow the navigation chain given in the quotes to find the new layers. I do however accept that we could have written a more descriptive changelog entry, we will try to improve this in future.
