### ISSUE TITLE
HTTP error 504 fetching aemo/v7/csv/all (again)

### ISSUE THREAD

**Issue by bje-** [TerriaJS/aremi-natmap#179]
The problem has reoccurred (see #175 for details). It last happened at `Tue, 31 Oct 2017 09:25:02 +1100 (AEDT)`.

**Comment by axman6** [comment]
@bje- Can you let me know if you see this again? I did something dumb and happened to lose the logs from the instance from this time period.

**Comment by bje-** [comment]
Shall do.

**Comment by axman6** [comment]
I should've mentioned, you should hit the new service we sent you (`services-<date...>.aremi.d61.io`). It may be a little slower because I'm also hitting it to try and make it produce a 504 too. (I wouldn't use the new service for the production version of your service, if you can run a second one to test that would be good, but would also like to know if you run into an issue with our production service)
