### ISSUE TITLE
AREMI v2017-11-13 pre-release test - Error loading layer - 2

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#187]
Error loading data layer

Layer: Renewable Energy/Bioenergy/National/Western Australia/Horticulture/Avocado Residue

![slide2](https://user-images.githubusercontent.com/22827786/32818139-a8e56c6e-ca15-11e7-82fb-76c48866855e.JPG)

**Comment by meh9** [comment]
Thanks.

These are old and rarely used, so I've removed them from the next release.

**Comment by meh9** [comment]
Oops, close the wrong issue.

**Comment by meh9** [comment]
The data custo

**Comment by meh9** [comment]
This is because the the automatic region mapping for this layer is trying to use 2016 SA2 codes when it should actually be using 2011 SA2 codes.

I've already notified the data custodian asking them to change it.

The only outcome in this case is that the single region mentioned in the Issue message is just not being shown.

**Comment by meh9** [comment]
The data custodian has now fixed the issue.
