### ISSUE TITLE
AREMI v2018-05-25 post-release test - Error loading all layers of the Renewable Energy/Bioenergy/Western Australia/Plantations group

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#239]
Error loading layer - 'An error occurred'
Layer: Renewable Energy/Bioenergy/Western Australia/Plantations/Hardwood NFI Plantations 2016

![slide17](https://user-images.githubusercontent.com/22827786/41638763-8ca233f4-744a-11e8-8eac-bff69e4c525c.JPG)

![slide8](https://user-images.githubusercontent.com/22827786/41638836-ee1138d8-744a-11e8-901f-9c6ffdbec4ca.JPG)

![slide9](https://user-images.githubusercontent.com/22827786/41638844-f45fc3da-744a-11e8-9379-32b202f0c5a3.JPG)

**Comment by AnaBelgun** [comment]
I think this is connected with the https://github.com/TerriaJS/terriajs/issues/3011

**Comment by meh9** [comment]
This is due to internal infrastructure setup. We have identified the issue and are waiting for our hosting provider to apply the fix.

**Comment by AnaBelgun** [comment]
The problem is that if the HTTP header "X-Forwarded-Proto" is set to "http" then www.agric.wa.gov.au will redirect forever.

To demonstrate:
X-Forwarded-Proto:https - the working case:
$ http --headers 'https://www.agric.wa.gov.au/geoserver/NFI/wms?service=WMS&version=1.3.0&request=GetCapabilities' X-Forwarded-Proto:https | head -n1
HTTP/1.1 200 OK

X-Forwarded-Proto:http - the problem case:

$ http --headers 'https://www.agric.wa.gov.au/geoserver/NFI/wms?service=WMS&version=1.3.0&request=GetCapabilities' X-Forwarded-Proto:http | head -n1
HTTP/1.1 302 https://www.agric.wa.gov.au/geoserver/NFI/wms?service=WMS&version=1.3.0&request=GetCapabilities

When set to "http" - even though we actually accessed it over HTTPS - we receive a 302 redirect to the exactly same URL that we accessed, if we follow the redirect then we get another redirect and so on ad infinitum.

**Comment by meh9** [comment]
This has now been fixed.
