### ISSUE TITLE
Investigate IDs of power plants in AEMO based service

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#310]
But owing to what looks like a transcription error, some datapoints appear to be missing. For example, there’s no live generation data for Ararat Wind Farm. 
I think it’s because the DUID is wrongly coded – it’s in there as ARFW1 when it should be ARWF1. 
 
I wonder if there are more errors like that? Other wind and solar farms appear to be missing: eg Sapphire (SAPHWF1), Silverton (STWF1), Bungala (BNGSF1).
 
![aremi duid](https://user-images.githubusercontent.com/18452161/48450412-2695ec80-e7fa-11e8-85cd-df4d366041d5.jpg)

**Comment by AnaBelgun** [comment]
@meh9 is it possible to have a look at this, as part of the AREMI release?

**Comment by meh9** [comment]
Re Ararat Wind Farm, it is likely that AEMO had indeed mistyped the DUID of this generator since it appears their spreadsheet is updated manually by a person - there are often errors in the spreadsheet. It has now been corrected to the expected `ARWF1` and I have confirmed that we have data all the way back to 2016-08-19.

Re the other 3 examples, it is likely that we just hadn't updated the list of generators that would enable us to show them. We now have data for all three:
1. SAPHWF1 from 2018-02-01
2. STWF1 from 2018-05-13
3. BNGSF1 from 2018-05-14
