### ISSUE TITLE
ABBA WA - Investigate issues with changed CSVs

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#335]
Here is the new an previous file. The file ending in DWv2 is the new file. All I have done is rename the display column to TOTAL_RESIDUES and the Timeframe column to PERIOD. For some layers I did add a dry weight t/yr if it was not there. Also I changed the total residues to t/yr for all residue types. For the Period column I changed it to reflect the period which the data represents, in most cases this is one year thus the  2015 – 2016. Interestingly some layers are doing different things but none appear to like the changes I did.  

data files here: https://drive.google.com/drive/folders/1w2-E3GCb-8UsvOGLrR9rj6QnmO56y19p

**Comment by AnaBelgun** [comment]
The ones that have a miss match between what is displayed in the datasets areas and what is in each location (LGA etc?) are;
•	Softwood
•	Hardwood
•	Municipal Shire Waste
•	Commercial and Industrial Waste
•	Construction and Demolition Waste
•	All horticultural layers
•	Cereal straw.

**Comment by reginapramesti** [comment]
I haven't looked into the Cereal Straw case, but I found out that the main reason behind the mismatch is that the columns are set to hidden in the catalogue files. For the Hardwood Plantation Residues, Softwood Plantation Residues and all Horticulture layers, they all follow the format where
https://github.com/TerriaJS/aremi-natmap/blob/345b36a134061d5fd1c663cb8ecb77d92c788df1/datasources/aremi/custodian/WA_Department_of_Primary_Industries_and_Regional_Development/common_data_wa_gov_au.ejs#L8-L17
the columns BIOMASS_DESCRIPTION, CROP_TYPE, REGION, RESIDUE_TYPE, RESIDUE_UNIT, SEASONALITY, TIMEFRAME, TOTAL_RESIDUES are hidden. 

For the Dairy Effluent, the columns that are set to hidden are the columns below:
https://github.com/TerriaJS/aremi-natmap/blob/345b36a134061d5fd1c663cb8ecb77d92c788df1/datasources/aremi/custodian/WA_Department_of_Primary_Industries_and_Regional_Development/Bio.ejs#L183-L188
which is why they don't appear on the left hand side, but appears on the `FeatureInfoPanel` when you click on one of the regions. The same idea applies to Municipal Shire Waste, Commercial and Industrial Waste, and Construction and Demolition Waste.

**Comment by AnaBelgun** [comment]
@meh9 we can reverse that setting right?

**Comment by meh9** [comment]
@AnaBelgun yeah no problem, we just need to figure out what is actually required - those are the settings we were instructed to use last time.

**Comment by AnaBelgun** [comment]
Updated visibility settings here: https://drive.google.com/file/d/1yIgAwQXq4S7Ne1f8qyZvUYW6HyYbl8Nc/view

**Comment by reginapramesti** [comment]
I've updated the visibility of the columns based on the given visibility settings, but with the following exceptions:
* Mechanically Harvested Vegetable Residue doesn't have the column "Number of businesses", but has a column "Number of properties", which is what I set to be visible.
* Pome Fruit Residue doesn't have the column "Total Production (T)", so only the other 3 columns are visible.

**Comment by AnaBelgun** [comment]
@reginapramesti thank you
They sent a new request: 
"For the cereal layer could you add production level as well please. Also when referring to what is visible I gather that the fields not listed will still be visible for individual LGA’s when clicked on. They will just be hidden as selectable display fields."

**Comment by reginapramesti** [comment]
> For the cereal layer could you add production level as well please.

Sure, this should be fine. I've applied the change to the PR. Feel free to merge it if they're fine with everything @AnaBelgun 

> Also when referring to what is visible I gather that the fields not listed will still be visible for individual LGA’s when clicked on. They will just be hidden as selectable display fields.

Yes, that's right.
