### ISSUE TITLE
Share broken on AREMI

### ISSUE THREAD

**Issue by AnaBelgun** [TerriaJS/aremi-natmap#378]
It seems that share functionality is broken for some/a layers on AREMI: https://nationalmap.gov.au/renewables/#share=s-oDPMo1jDBBtwBNhD

Go to any data layer, share, open in new tab; error message: 

![image](https://user-images.githubusercontent.com/18452161/60475053-ba002d00-9cb8-11e9-8c46-4856199d1384.png)

**Comment by AnaBelgun** [comment]
@kring would you please finalise the investigation on this one?

**Comment by kring** [comment]
Last week, AREMI was showing an error when visiting the share link above. The error was related to accessing https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Hay_Silage_Residues/MapServer, and the server was reporting an error for that layer. Today its working because that server is happy again. But AREMI is still accessing that URL when visiting this share link, which is surprising because nothing cropping-related is included in the share link at all.

Here's what's happening:
* In the latest version of the AREMI catalog up on nationalmap.gov.au, the `New South Wales -> Cropping -> All Residues - Cropping Overview` dataset is an `esri-mapServer-group`.
* The share link references an _old_ version of the catalog, http://static.aremi.data61.io/init/aremi-2019-02-18-7754863eb7bf0df14dfea88193a6baaddbfcecbf.json.
* AREMI does not filter out old versions of the catalog the way NationalMap does. It has the code to do so (https://github.com/TerriaJS/aremi-natmap/blob/c5445aeefd5b2b446e4a620e0019d56d43eca5c4/index.js#L64), but it has not been adapted to the AREMI catalog URLs.
* So AREMI loads the old catalog. In the old catalog, the `All Residues - Cropping Overview` dataset is a normal `group` rather than a MapServer group. And it has an item inside it called `SA2 Total All Straw, Hay and Silage (t)`.
* In order to load the JSON for an item inside a group, Terria first loads the parent group. So Terria loads `All Residues - Cropping Overview`. In the new catalog that's a MapServer group, so it does a request to https://spatial.industry.nsw.gov.au/arcgis/rest/services/Bioenergy_Assessment/Cropping_All_Straw_Hay_Silage_Residues/MapServer. If that URL fails, the group load fails, and so the JSON init fails.

So the solution here is adapt this code https://github.com/TerriaJS/aremi-natmap/blob/c5445aeefd5b2b446e4a620e0019d56d43eca5c4/index.js#L64 for the AREMI catalog URLs. This will likely fix other bugs as well where the catalog appears to (partially?) revert to an old version when visiting share URLs.

**Comment by AnaBelgun** [comment]
@krin Is the same happening with this share link (pointing to a different dataset/server): https://nationalmap.gov.au/renewables/#share=s-7olCH2Vgiye5UYwe

**Comment by kring** [comment]
> Is the same happening with this share link (pointing to a different dataset/server): 

Yes looks that way @AnaBelgun.
