### ISSUE TITLE
AREMI 2017-04-24 pre-release test - Placement of Layer/Legend boxes on the left panel

### ISSUE THREAD

**Issue by EhsanCanberra** [TerriaJS/aremi-natmap#96]
Is the order of placing the Layer/Legend boxes on the left panel consistent?

The most recent layer added to map view will always be placed on top of the pile - this is expected by the user or what happens now after the user selects a top level catalogue entry. However, when second or third level catalogue layers are opened this may not be the case.

Example: 
- Add (1) 'Biogas Facilities' layer
- Add (2) 'Biosolids - infrastructure' layer
- Result: (2) is placed below (1) not on top.

What is the rule followed here? Higher level layers go on the top and lower level layers go to the bottom? If this is the case a lower level entry may go at the bottom of a long list of entries not visible to the user - expecting the latest entry to be on the top of list on the visible part of the panel.

![aremi-2017-04-24-issue-6](https://cloud.githubusercontent.com/assets/22827786/25606130/3504aab0-2f53-11e7-8673-f662a4b16d24.jpg)

**Comment by meh9** [comment]
The reason the Biosolids is appearing below the Facilities layers is because Biosolids is a raster layer and Facilities is a natively drawn layer. Unfortunately, it's very difficult (Impossible? Any comments, @kring?) to layer raster layers above natively drawn layers in Cesium, and therefore raster layers have to be placed underneath.
